version: "3.9"

services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment: 
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=survey
    volumes:
      - ./postgres-db:/var/lib/postgresql/data
  back:
    build: ./empth-back
    image: back
    container_name: back
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - 4100:4100
  front:
    build: ./front-empth
    image: front
    container_name: front
    ports:
      - 4200:4200
    restart: unless-stopped
    depends_on:
      - back